RR01:
  mot:
    ros__parameters:
      tau_local: 2.0
      tau_global: .75
      alpha: 2000
      kappa: 4
      n_meas_to_init_track: 3
      robot_id: 1
      pose_from_odom: False
      pose_topic: "/RR01/world"
      mot_dt: .1
RR04:
  mot:
    ros__parameters:
      tau_local: 2.0
      tau_global: .75
      alpha: 2000
      kappa: 4
      n_meas_to_init_track: 3
      robot_id: 1
      pose_from_odom: False
      pose_topic: "/RR04/world"
      mot_dt: .1
RR06:
  mot:
    ros__parameters:
      tau_local: 2.0
      tau_global: .75
      alpha: 2000
      kappa: 4
      n_meas_to_init_track: 3
      robot_id: 1
      pose_from_odom: False
      pose_topic: "/RR06/world"
      mot_dt: .1
RR08:
  mot:
    ros__parameters:
      tau_local: 2.0
      tau_global: .75
      alpha: 2000
      kappa: 4
      n_meas_to_init_track: 3
      robot_id: 1
      pose_from_odom: False
      pose_topic: "/RR08/world"
      mot_dt: .1